# Copyright 2019 Benbuck Nason

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2

      - name: Install node modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run compile

      - name: Test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: npm run test

      - name: Package
        run: npm run package

#      - name: Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: package
#          path: findallinfile-*.vsix
